Update 2018-00-00-havanar.md
forwards/website_source pull request #33
Opened 2018-06-19 09:12 UTC by TanjaKec

Final version approved by Julie and Ziv

2018-06-20 20:01 UTC, missaugustina commented
I restarted the build, it looks like it failed during setup (apt-get etc...)

2018-06-25 18:30 UTC, hturner requested changes
We will need a banner image for the blog as well - I don't know if Ziv has anything? Else maybe @missaugustina can advise?

2018-06-25 18:30 UTC, hturner commented on content/blog/2018-00-00-havanar.md
> +The first meeting of R users in Cuba, HavanaR! Club 2018, will take place From 29-10-2018 to 02-11-2018. The workshop is organized jointly by the Group of Probability and Statistics of Universidad de
On our own website the taskforce can be referred to simply as "Forwards". (This is the official name, but often the R is added to clarify what we're about, especially in a general environment such as Twitter, vs a specific R environment, such as useR!).

2018-06-25 18:30 UTC, hturner commented on content/blog/2018-00-00-havanar.md
> +All updates about the workshop will be anounced on facebook page (https://www.facebook.com/ER-BioStat-1463845487001786/) and Twitter (@erbiostat).
"the Facebook page"

2018-06-25 18:32 UTC, hturner commented
I'm not sure our build works with pull requests from accounts outside the Forwards GitHub organisation. There's no harm in accepting a pull request to a branch though as that won't get pushed to production. So maybe when @TanjaKec has made the minor corrections I suggested, this can be accepted and we can take it from there? @TanjaKec should be part of the org, I will chase that up.

2018-07-02 19:33 UTC, hturner commented
Okay merging this into branch for finishing off

2018-07-02 19:33 UTC, merged

2018-07-11 16:45 UTC, missaugustina commented
Looks good to me, sorry for the late response!

2018-07-11 16:45 UTC, missaugustina commented
Looking at this now, sorry for the delay!

2018-07-11 16:48 UTC, missaugustina reviewed
Agree with Heather's comments, I think just those small edits and this should be good.