Update blog; Added the R in Africa blog
forwards/website_source pull request #90
Opened 2019-11-15 19:15 UTC by lornamariak

@hturner and @Shakyrah please go through this blog and let me know if it looks good to publish.

2019-11-22 16:24 UTC, hturner requested changes
In addition
- rename image files `.jpg` to match the file names in the markdown
- use the script in `website_source\R\optimize_photo.R` to reduce the image file sizes (should be <100kb, the events one is okay)
- try to preview the site on your laptop or on https://rforwards-auto.github.io/ to check it builds correctly (it doesn't work at the moment due to the problem in the YAML.

Otherwise, the content is good and the photos are really great!

2019-11-22 16:24 UTC, hturner commented on content/blog/2019-11-15-the-state-of-r-in-africa.md
> +title: The-state-of-R-in-Africa
```suggestion
title: The state of R in Africa
```

2019-11-22 16:24 UTC, hturner commented on content/blog/2019-11-15-the-state-of-r-in-africa.md
> +banner:"/images/blog/The-state-of-R-in-Africa/banner.jpg"
```suggestion
banner: "/images/blog/The-state-of-R-in-Africa/banner.jpg"
```

2019-11-22 16:24 UTC, hturner commented on content/blog/2019-11-15-the-state-of-r-in-africa.md
> +banner:"/images/blog/The-state-of-R-in-Africa/banner.jpg"
A space is needed here for the YAML to parse properly

2019-11-22 16:24 UTC, hturner commented on content/blog/2019-11-15-the-state-of-r-in-africa.md
> +title: The-state-of-R-in-Africa
spaces are needed here as this is the title used in the blog post

2019-11-22 16:24 UTC, hturner commented on content/blog/2019-11-15-the-state-of-r-in-africa.md
> +##Growth of the R ecosystem in Africa
```suggestion
## Growth of the R ecosystem in Africa 
```

2019-11-22 16:24 UTC, hturner commented on content/blog/2019-11-15-the-state-of-r-in-africa.md
> +##Growth of the R ecosystem in Africa
spaces are needed after `##` otherwise the title is not recognised when the markdown is rendered.

2019-11-22 16:24 UTC, hturner commented on content/blog/2019-11-15-the-state-of-r-in-africa.md
> +An effective model to enter the Africa developer ecosystem relies on a small group of enthusiasts creating a safe learning environment, documenting and sharing their learning experiences and slowly a
```suggestion
An effective model to enter the Africa developer ecosystem relies on a small group of enthusiasts creating a safe learning environment, documenting and sharing their learning experiences and slowly attracting interested learners. Africa R users group are using this model to introduce R as a language for data science by organising communities across different cities in Africa.
```

2019-11-22 16:24 UTC, hturner commented on content/blog/2019-11-15-the-state-of-r-in-africa.md
> +The growth of technical talent in Africa positively correlates with the growth of communities around certain technologies/tools/languages. These communities are creating a long table to share opportu
```suggestion
The growth of technical talent in Africa positively correlates with the growth of communities around certain technologies/tools/languages. These communities are creating a long table to share opportunities on the continent. When we shift the spotlight to R in the Africa tech community we see an evolution in useR groups of not only academic researchers using R in their PhD or master’s degrees but also people using R at their workplaces or for their freelance projects. 
```

2019-11-22 16:24 UTC, hturner commented on content/blog/2019-11-15-the-state-of-r-in-africa.md
> +Some of the chapters include [Kampala](https://mobile.twitter.com/Rladieskampala),[Lagos](https://mobile.twitter.com/LagosRUsers),[Dar es salaam](https://mobile.twitter.com/daR_users), [Abidjan](http
Perhaps make clear which are general R User Groups and which are R-Ladies groups?

2019-11-22 16:24 UTC, hturner commented on content/blog/2019-11-15-the-state-of-r-in-africa.md
> +SatRday: The R community in Johanessburg and Kampala have both hosted satRday events in April 2019 and May 2019 respectively. These events featured light talks and hands-on workshops for R users and
```suggestion
SatRday: The R community in Johanessburg and Kampala have both hosted satRday events in April 2019 and May 2019 respectively. These events featured lightning talks and hands-on workshops for R users and were free. These have been the biggest R focused events on the continent for the year and the hope is they will spread to other regional hosts in the coming year. 
```

2019-11-22 16:24 UTC, hturner commented on content/blog/2019-11-15-the-state-of-r-in-africa.md
> +##Events
```suggestion
## Events
```

2019-11-22 16:24 UTC, hturner commented on content/blog/2019-11-15-the-state-of-r-in-africa.md
> +##The Future
```suggestion
## The Future
```

2019-11-22 16:24 UTC, hturner commented on content/blog/2019-11-15-the-state-of-r-in-africa.md
> +R as a statistical programming language has a great value to the data science community on the continent and useRs to showing this value through their work, research and education. Most useR groups i
```suggestion
R as a statistical programming language has a great value to the data science community on the continent and useRs are showing this value through their work, research and education. Most useR groups in Africa currently focus on developing material that shows the amazing facets of R, rendering it as an option on the table for potential clients and the community. We are starting to see R cross paths with other programming languages thus raising a need to create room for it in learning and early career choices through building communities, mentoring talent and eventually powering businesses.
```

2019-11-22 16:24 UTC, hturner commented on content/blog/2019-11-15-the-state-of-r-in-africa.md
> +Follow the [AfricaR](https://mobile.twitter.com/AfricaRUsers)  and individual chapters on their social media to view the most recent updates on events.
```suggestion
Follow [AfricaR](https://mobile.twitter.com/AfricaRUsers)  and individual chapters on their social media to view the most recent updates on events.
```

2019-11-26 13:16 UTC, lornamariak commented
Fixed all the issues. It does show the preview on https://rforwards-auto.github.io/blog/2019/11/15/the-state-of-r-in-africa/

2019-11-27 08:19 UTC, merged